#
version: '3.1'

services:
  teste:
    container_name: teste
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME=root
      - TASK_SCHEDULE=* * * * *
      - COMMAND=node --version 
   
    entrypoint: ["tail", "-f", "/dev/null"]

